server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username:postgres_user
    password:S3cret

  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update