# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
  
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  
  - name: run-docker-compose
    init: echo 'run docker compose'
    # docker-compose up
  #- name: cql_cassandra
  #  init: docker exec -it cassandra cqlsh
    # CREATE KEYSPACE spring_cassandra WITH replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-lombok
    - eamodio.gitlens
    - felipecaputo.git-project-manager
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - evondev.indent-rainbow-palettes
    - donjayamanne.git-extension-pack
    - esbenp.prettier-vscode
    - redhat.vscode-xml
    - rangav.vscode-thunder-client
    - developersoapbox.vscode-springboot-developer-pack
    - ms-azuretools.vscode-dapr
    - bierner.markdown-preview-github-styles
    - oderwat.indent-rainbow
    - cweijan.git-graph-history
    - mhutchie.git-graph
    - ms-vscode.makefile-tools
    - mongodb.mongodb-vscode 
