# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: run-mysl
    init: echo 'init script' # runs during prebuild
    #     mysql -e "CREATE DATABASE order_service;" &&
    #     mysql -e "CREATE USER 'newuser' @ 'localhost' IDENTIFIED BY 'my_password';" &&
    #     mysql -e "GRANT ALL PRIVILEGES ON order_service.* TO 'newuser'@'localhost';"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
