version: "3"
services:
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    network_mode: host
#    restart: always
#    ports:
#     - 27017:27017

  my-mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=person_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - /workspace/data/db:/data/db
      # named volumes
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
