server:
  port: 8087

spring:
  application:
    name: mongodb-example

  data:
    mongodb:
      host: mongodb
      port: 27017
      username: admin
      password: admin
      database: person_db
