server:
  port: 8087

spring:
  application:
    name: mongodb-example

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      database: testdb
